# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0008_bot_exit_policy_bot_safety_net_pct_bot_signal_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('token', models.CharField(db_index=True, max_length=43, unique=True)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('secret_fingerprint', models.CharField(blank=True, max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('require_signature', models.BooleanField(default=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('replay_window_seconds', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_source_config', to='bots.bot')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('remote_addr', models.CharField(blank=True, max_length=64)),
                ('signal_id', models.CharField(max_length=140)),
                ('verb', models.CharField(blank=True, max_length=12)),
                ('verdict', models.CharField(choices=[('accepted', 'Routed'), ('duplicate', 'Duplicate — already handled'), ('noop', 'Already in that state'), ('rejected', 'Refused')], max_length=12)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_events', to='bots.botrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tradesignals.signalsource')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', '-received_at'], name='tradesignal_source__e0d280_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'signal_id'), name='signals_event_unique_per_source')],
            },
        ),
    ]
