# Generated by Django 5.1.4 on 2026-07-17 16:05

from django.db import migrations, models


def backfill_admin(apps, schema_editor):
    """Existing users predate the investor concept — treat them as admins."""
    User = apps.get_model('accounts', 'User')
    User.objects.update(role='admin')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor')], default='investor', help_text='Platform role: admins publish strategies; investors subscribe.', max_length=16),
        ),
        migrations.RunPython(backfill_admin, noop_reverse),
    ]
