# Generated by Django 5.1.4 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Force password change on next login (set when an admin creates/resets an account).",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("investor", "Investor")],
                default="investor",
                max_length=16,
            ),
        ),
    ]
