# Generated by Django 5.1.4 on 2026-07-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_termsacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor')], default='investor', help_text='Platform role: admins publish strategies; investors subscribe.', max_length=16),
        ),
    ]
