# Generated by Django 5.1.5 on 2026-08-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profitsplit_fundmovement'),
        ('trading', '0005_tradeleg_sltp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=8)),
                ('category', models.CharField(choices=[('TRADE', 'Trade'), ('EXCHANGE', 'Exchange'), ('SYSTEM', 'System'), ('AUTH', 'Auth'), ('MARKET_DATA', 'Market Data'), ('ENGINE', 'Engine'), ('ADMIN', 'Admin')], max_length=16)),
                ('source', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('exchange', models.CharField(blank=True, max_length=20, null=True)),
                ('error_code', models.CharField(blank=True, max_length=60, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='accounts.connectedaccount')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='trading.trade')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='logging_log_level_077e8c_idx'), models.Index(fields=['category', 'timestamp'], name='logging_log_categor_e86803_idx'), models.Index(fields=['account', 'timestamp'], name='logging_log_account_763622_idx')],
            },
        ),
    ]
