# Generated by Django 5.1.5 on 2026-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logentry',
            name='logging_log_account_763622_idx',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='trade',
        ),
        migrations.AddField(
            model_name='logentry',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='trade_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['account_id', 'timestamp'], name='logging_log_account_763622_idx'),
        ),
    ]
