# Generated by Django 5.1.5 on 2026-08-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0002_remove_logentry_logging_log_account_763622_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('TRADE', 'Trade'), ('EXCHANGE', 'Exchange'), ('SYSTEM', 'System'), ('AUTH', 'Auth'), ('MARKET_DATA', 'Market Data'), ('ENGINE', 'Engine'), ('ADMIN', 'Admin'), ('BOT', 'Bot'), ('STRATEGY', 'Strategy')], max_length=16),
        ),
    ]
