# Generated by Django 5.1.4 on 2026-06-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=8)),
                ('event', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', 'created_at'], name='execution_e_strateg_02dd0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okx_order_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('client_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('order_type', models.CharField(help_text='market, limit, ...', max_length=16)),
                ('size', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('filled_size', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Raw OKX payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='strategies.strategy')),
            ],
            options={
                'indexes': [models.Index(fields=['strategy', 'created_at'], name='execution_o_strateg_9e638e_idx')],
            },
        ),
    ]
