# Generated by Django 5.1.4 on 2026-06-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(help_text='Strategy type identifier.', max_length=64)),
                ('symbol', models.CharField(help_text='e.g. BTC-USDT', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='credentials.exchangecredential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'strategies',
            },
        ),
        migrations.CreateModel(
            name='StrategyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(blank=True, default=dict)),
                ('last_signal', models.CharField(blank=True, default='', max_length=64)),
                ('pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='strategies.strategy')),
            ],
        ),
    ]
