# Generated by Django 5.1.4 on 2026-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='validation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='validation_status',
            field=models.CharField(blank=True, default='', help_text='ok | error', max_length=16),
        ),
    ]
