# Generated by Django 5.1.4 on 2026-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0002_strategy_source_strategy_validation_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="timeframe",
            field=models.CharField(default="1m", max_length=16),
        ),
        migrations.AddField(
            model_name="strategy",
            name="warmup_bars",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="strategystate",
            name="last_bar_ts",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="strategystate",
            name="live_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="strategystate",
            name="live_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
