# Generated by Django 5.1.4 on 2026-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_strategy_credential_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Admin master strategy whose signals fan out to investors.'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='published',
            field=models.BooleanField(default=False, help_text='Visible in the investor marketplace for subscription.'),
        ),
    ]
