# Generated by Django 5.1.4 on 2026-06-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('okx', 'OKX')], default='okx', max_length=16)),
                ('label', models.CharField(help_text='Human-friendly name.', max_length=64)),
                ('api_key_enc', models.BinaryField()),
                ('api_secret_enc', models.BinaryField()),
                ('passphrase_enc', models.BinaryField()),
                ('is_demo', models.BooleanField(default=True, help_text='OKX demo (paper) trading flag.')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Scopes reported by the exchange, e.g. read/trade.')),
                ('is_active', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'exchange', 'label'), name='uniq_user_exchange_label')],
            },
        ),
    ]
