# Generated by Django 5.1.4 on 2026-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_hyperliquid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangecredential",
            name="agent_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Derived agent wallet address (set on verify).",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="permissions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Agent metadata reported on verify."
            ),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="wallet_address",
            field=models.CharField(
                help_text="Master wallet address (read-only monitoring; not stored encrypted).",
                max_length=42,
            ),
        ),
    ]
