# Generated by Django 5.1.4 on 2026-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_exchangecredential_agent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredential',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Public API key (Tabdeal and other Binance-style exchanges).', max_length=128),
        ),
        migrations.AddField(
            model_name='exchangecredential',
            name='api_secret_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='agent_private_key_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='exchange',
            field=models.CharField(choices=[('hyperliquid', 'Hyperliquid'), ('tabdeal', 'Tabdeal')], default='hyperliquid', max_length=16),
        ),
        migrations.AlterField(
            model_name='exchangecredential',
            name='wallet_address',
            field=models.CharField(blank=True, default='', help_text='HL master wallet address (read-only monitoring; not encrypted).', max_length=42),
        ),
    ]
