# Generated by Django 5.1.4 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0003_alter_exchangecredential_agent_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangecredential",
            name="api_key_enc",
            field=models.BinaryField(
                blank=True,
                default=b"",
                help_text="Encrypted REST API key (e.g. Tabdeal). Empty for Hyperliquid.",
            ),
        ),
        migrations.AddField(
            model_name="exchangecredential",
            name="api_secret_enc",
            field=models.BinaryField(
                blank=True,
                default=b"",
                help_text="Encrypted REST API secret (e.g. Tabdeal). Empty for Hyperliquid.",
            ),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="agent_private_key_enc",
            field=models.BinaryField(
                blank=True,
                default=b"",
                help_text="Hyperliquid agent private key. Empty for other exchanges.",
            ),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="exchange",
            field=models.CharField(
                choices=[("hyperliquid", "Hyperliquid"), ("tabdeal", "Tabdeal")],
                default="hyperliquid",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="exchangecredential",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Master wallet address (read-only monitoring; not stored encrypted). Hyperliquid only.",
                max_length=42,
            ),
        ),
    ]
