# Generated by Django 5.1.5 on 2026-08-26 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login_ok', 'Signed in'), ('login_failed', 'Sign-in refused'), ('login_locked', 'Sign-in rate limited'), ('logout', 'Signed out'), ('mfa_ok', 'Second factor accepted'), ('mfa_failed', 'Second factor refused'), ('mfa_enrolled', 'Second factor enrolled'), ('mfa_disabled', 'Second factor removed'), ('recovery_used', 'Recovery code used'), ('trust_issued', 'Browser remembered'), ('new_device', 'Sign-in from a new device'), ('session_revoked', 'Session ended remotely'), ('session_expired', 'Session timed out'), ('ip_blocked', 'Address not on the allowlist'), ('rate_limited', 'Write rate limited'), ('step_up_ok', 'Password re-entered'), ('step_up_failed', 'Password re-entry refused'), ('step_up_required', 'Password re-entry demanded'), ('policy_changed', 'Security setting changed')], db_index=True, max_length=24)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('two_factor', models.BooleanField(default=False)),
                ('trusted_devices', models.BooleanField(default=False)),
                ('login_rate_limit', models.BooleanField(default=False)),
                ('new_device_notice', models.BooleanField(default=False)),
                ('idle_timeout', models.BooleanField(default=False)),
                ('single_session', models.BooleanField(default=False)),
                ('ip_allowlist', models.BooleanField(default=False)),
                ('step_up', models.BooleanField(default=False)),
                ('audit_log', models.BooleanField(default=False)),
                ('admin_write_rate_limit', models.BooleanField(default=False)),
                ('csp_mode', models.CharField(choices=[('off', 'Off'), ('report', 'Report only'), ('enforce', 'Enforced')], default='off', max_length=8)),
                ('login_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('login_window_seconds', models.PositiveIntegerField(default=300)),
                ('login_lockout_seconds', models.PositiveIntegerField(default=900)),
                ('idle_timeout_minutes', models.PositiveIntegerField(default=480)),
                ('session_max_hours', models.PositiveIntegerField(default=336)),
                ('trusted_device_days', models.PositiveSmallIntegerField(default=30)),
                ('step_up_grace_seconds', models.PositiveIntegerField(default=300)),
                ('admin_write_max_per_minute', models.PositiveSmallIntegerField(default=60)),
                ('allowed_ips', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'security policy',
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recovery_codes', models.JSONField(blank=True, default=list)),
                ('recovery_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('last_step', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
    ]
