# Generated by Django 5.1.5 on 2026-08-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=8)),
                ('market', models.CharField(default='futures', max_length=10)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('sl_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tp_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sltp_basis', models.CharField(default='price', max_length=10)),
                ('admin_entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('fanout_ms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('dispatch_ms', models.FloatField(blank=True, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('sltp_attached', models.BooleanField(default=False)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_legs', to='accounts.connectedaccount')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trading.trade')),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(fields=('trade', 'account'), name='one_leg_per_account')],
            },
        ),
    ]
