# Generated by Django 5.1.5 on 2026-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_killswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('phase', models.CharField(choices=[('symbols', 'Downloading pairs'), ('candles', 'Downloading history'), ('done', 'Complete')], default='symbols', max_length=10)),
                ('symbols_found', models.PositiveIntegerField(default=0)),
                ('series_total', models.PositiveIntegerField(default=0)),
                ('series_done', models.PositiveIntegerField(default=0)),
                ('bars_written', models.PositiveBigIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=32)),
                ('base', models.CharField(max_length=20)),
                ('quote', models.CharField(max_length=20)),
                ('market', models.CharField(max_length=10)),
                ('native_symbol', models.CharField(blank=True, max_length=48)),
                ('price_tick', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('qty_step', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('min_qty', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('min_notional', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('max_leverage', models.PositiveIntegerField(default=0)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['market', 'active', '-volume_24h'], name='trading_exc_market_dbf0be_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market', 'symbol'), name='unique_symbol_per_exchange')],
            },
        ),
        migrations.CreateModel(
            name='StoredCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=32)),
                ('market', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=6)),
                ('open_time', models.BigIntegerField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
            ],
            options={
                'ordering': ['open_time'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'market', 'open_time'], name='trading_sto_symbol_9f6eee_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market', 'symbol', 'interval', 'open_time'), name='unique_bar_per_series')],
            },
        ),
    ]
