# Generated by Django 5.1.5 on 2026-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_marketdatasync_exchangesymbol_storedcandle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('days', models.PositiveIntegerField(default=1)),
                ('intervals', models.CharField(blank=True, max_length=200)),
                ('priority_interval', models.CharField(default='1m', max_length=6)),
                ('series_done', models.PositiveIntegerField(default=0)),
                ('series_total', models.PositiveIntegerField(default=0)),
                ('bars_written', models.PositiveBigIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
