# Generated by Django 5.1.5 on 2026-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_historyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeleg',
            name='sltp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
