# Generated by Django 5.1.5 on 2026-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradeleg_sltp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(default='market', max_length=10),
        ),
    ]
