# Generated by Django 5.1.5 on 2026-08-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trade_order_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storedcandle',
            index=models.Index(fields=['market', 'symbol', 'interval', '-open_time'], name='candle_series_recent_idx'),
        ),
    ]
