# Generated by Django 5.1.5 on 2026-08-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('trading', '0007_storedcandle_candle_series_recent_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='bot_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='bots.botrun'),
        ),
    ]
