# Generated by Django 5.1.15 on 2026-09-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_trade_bot_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='open_fraction',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradeleg',
            name='entry_qty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tradeleg',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.CreateModel(
            name='TradeReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=24)),
                ('to_fraction', models.DecimalField(decimal_places=8, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('source_code', models.CharField(blank=True, max_length=40)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='trading.tradeleg')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
