# Generated by Django 5.1.15 on 2026-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_trade_open_fraction_tradeleg_entry_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exit_policy',
            field=models.CharField(default='protected', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='safety_net_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
