# Generated by Django 5.1.15 on 2026-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_trade_exit_policy_trade_safety_net_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=32)),
                ('market', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=6)),
                ('earliest', models.BigIntegerField()),
                ('proved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'market', 'symbol', 'interval'), name='unique_series_floor')],
            },
        ),
    ]
