# Generated by Django 5.1.5 on 2026-08-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0007_storedcandle_candle_series_recent_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=32)),
                ('interval', models.CharField(default='1h', max_length=6)),
                ('market', models.CharField(default='futures', max_length=10)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('sl_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tp_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('input_values', models.JSONField(blank=True, default=dict)),
                ('risk_config', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('paper', 'Paper'), ('live', 'Live'), ('stopped', 'Stopped')], default='draft', max_length=10)),
                ('dry_run', models.BooleanField(default=True)),
                ('drills_fired', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('consecutive_losses', 'Consecutive Losses'), ('drawdown', 'Drawdown'), ('feed_gap', 'Feed Gap'), ('script_error', 'Script Error'), ('state_disagreement', 'State Disagreement'), ('trade_rate', 'Trade Rate'), ('no_bars', 'No Bars'), ('halt', 'Halt'), ('manual', 'Manual'), ('risk_gate', 'Risk Gate')], default='', max_length=24)),
                ('stop_detail', models.TextField(blank=True)),
                ('warmup_bars', models.PositiveIntegerField(default=0)),
                ('feed_source', models.CharField(blank=True, max_length=12)),
                ('last_bar_time', models.BigIntegerField(blank=True, null=True)),
                ('peak_equity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('consecutive_losses', models.PositiveIntegerField(default=0)),
                ('recoveries', models.PositiveIntegerField(default=0)),
                ('unplanned_recoveries', models.PositiveIntegerField(default=0)),
                ('feed_gaps', models.PositiveIntegerField(default=0)),
                ('feed_gaps_repaired', models.PositiveIntegerField(default=0)),
                ('halt_drills', models.PositiveIntegerField(default=0)),
                ('divergences', models.PositiveIntegerField(default=0)),
                ('bars_evaluated', models.PositiveBigIntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='bots.bot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BotBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_time', models.BigIntegerField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('plots', models.JSONField(blank=True, default=dict)),
                ('intent', models.JSONField(blank=True, default=dict)),
                ('evaluation_ms', models.FloatField(blank=True, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='bots.botrun')),
            ],
            options={
                'ordering': ['-bar_time'],
            },
        ),
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_time', models.BigIntegerField()),
                ('action_type', models.CharField(choices=[('open', 'Open'), ('amend', 'Amend'), ('close', 'Close'), ('shadow', 'Shadow')], max_length=8)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('intent', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_actions', to='trading.trade')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bots.botrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('source', models.TextField()),
                ('parsed_ok', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('inputs_schema', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bots.strategy')),
            ],
            options={
                'ordering': ['strategy', '-version'],
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='bots.strategyversion'),
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('interval', models.CharField(max_length=6)),
                ('market', models.CharField(default='futures', max_length=10)),
                ('from_time', models.BigIntegerField()),
                ('to_time', models.BigIntegerField()),
                ('input_values', models.JSONField(blank=True, default=dict)),
                ('bars', models.PositiveIntegerField(default=0)),
                ('trades', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('trade_log', models.JSONField(blank=True, default=list)),
                ('intent_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='bots.strategyversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='botrun',
            index=models.Index(fields=['bot', '-started_at'], name='bots_botrun_bot_id_80d2be_idx'),
        ),
        migrations.AddIndex(
            model_name='botbar',
            index=models.Index(fields=['run', '-bar_time'], name='bots_botbar_run_id_161f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='botbar',
            constraint=models.UniqueConstraint(fields=('run', 'bar_time'), name='bots_bar_unique_per_run'),
        ),
        migrations.AddIndex(
            model_name='botaction',
            index=models.Index(fields=['run', '-bar_time'], name='bots_botact_run_id_aa0941_idx'),
        ),
        migrations.AddIndex(
            model_name='botaction',
            index=models.Index(fields=['run', 'settled_at'], name='bots_botact_run_id_a59bf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyversion',
            constraint=models.UniqueConstraint(fields=('strategy', 'version'), name='bots_version_unique_per_strategy'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['state'], name='bots_bot_state_72c446_idx'),
        ),
    ]
