# Generated by Django 5.1.15 on 2026-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyversion',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='strategyversion',
            name='property_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
