# Generated by Django 5.1.15 on 2026-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_strategy_version_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='property_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='botaction',
            name='action_type',
            field=models.CharField(choices=[('open', 'Open'), ('amend', 'Amend'), ('close', 'Close'), ('reduce', 'Reduce'), ('shadow', 'Shadow')], max_length=8),
        ),
    ]
