# Generated by Django 5.1.15 on 2026-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_backtestjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='gate_enforced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='gate_waived',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
