# Generated by Django 5.1.15 on 2026-09-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0005_bot_gate_enforced_bot_gate_waived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategyversion",
            name="inputs_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="InputPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presets",
                        to="bots.strategy",
                    ),
                ),
            ],
            options={
                "ordering": ["strategy", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("strategy", "name"), name="bots_preset_unique_per_strategy"
                    )
                ],
            },
        ),
    ]
