# Generated by Django 5.1.15 on 2026-09-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_strategyversion_inputs_schema_inputpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrun',
            name='started_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='botrun',
            name='stopped_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
