# Generated by Django 5.1.15 on 2026-09-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_botrun_started_by_botrun_stopped_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='exit_policy',
            field=models.CharField(choices=[('protected', 'Fixed SL/TP'), ('strategy_managed', 'Strategy decides the exit')], default='protected', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='safety_net_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='signal_source',
            field=models.CharField(choices=[('pine', 'Pine script'), ('webhook', 'External webhook')], default='pine', max_length=12),
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='bots.strategyversion'),
        ),
    ]
