# Generated by Django 5.1.15 on 2026-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_bot_exit_policy_bot_safety_net_pct_bot_signal_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrun',
            name='manual_flat_bar',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botrun',
            name='manual_flat_side',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
