# Generated by Django 5.1.4 on 2026-06-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0002_strategy_source_strategy_validation_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(blank=True, default='', max_length=16)),
                ('range_start', models.DateTimeField(blank=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('size', models.DecimalField(decimal_places=8, max_digits=24)),
                ('pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('entry_bar', models.IntegerField()),
                ('exit_bar', models.IntegerField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='transpiler.backtest')),
            ],
        ),
    ]
