# Generated by Django 5.1.4 on 2026-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transpiler', '0002_backtest_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttrade',
            name='exit_reason',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='limit_px',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='stop_px',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
    ]
