# Generated by Django 5.1.5 on 2026-08-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('exchange', models.CharField(choices=[('hyperliquid', 'Hyperliquid'), ('bybit', 'Bybit'), ('binance', 'Binance'), ('okx', 'OKX'), ('gateio', 'Gate.io'), ('kucoin', 'KuCoin'), ('toobit', 'Toobit'), ('lbank', 'LBank'), ('paper', 'Paper (demo)')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=10)),
                ('testnet', models.BooleanField(default=False)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('api_secret_encrypted', models.TextField(blank=True)),
                ('api_passphrase_encrypted', models.TextField(blank=True)),
                ('wallet_address', models.CharField(blank=True, max_length=64)),
                ('credential_expires_at', models.DateTimeField(blank=True, null=True)),
                ('key_fingerprint', models.CharField(blank=True, editable=False, max_length=16)),
                ('withdrawal_check_passed', models.BooleanField(default=False, help_text='Spec §7: verified trade-only, no withdrawal rights.')),
                ('last_balance', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('last_balance_asset', models.CharField(blank=True, max_length=12)),
                ('last_balance_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('eligible_from', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['exchange', 'label'],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'label'), name='unique_account_label_per_exchange')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.connectedaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
