# Generated by Django 5.1.5 on 2026-08-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='withdrawal_checked_at',
            field=models.DateTimeField(blank=True, help_text='When the spec §7 permission check last ran against the exchange. Null means never — see clean().', null=True),
        ),
    ]
