# Generated by Django 5.1.5 on 2026-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_connectedaccount_withdrawal_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
