# Generated by Django 5.1.5 on 2026-08-16 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_connectedaccount_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitSplit',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('investor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trader', models.DecimalField(decimal_places=2, max_digits=5)),
                ('programmer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FundMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Always positive; the direction lives in ``kind``.', max_digits=24)),
                ('asset', models.CharField(default='USDT', max_length=12)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_movements', to='accounts.connectedaccount')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['account', 'occurred_at'], name='accounts_fu_account_05ee5d_idx')],
            },
        ),
    ]
