# Generated by Django 5.1.5 on 2026-08-19 23:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_panelsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='last_equity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='ledger_cursor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='ledger_cursor_equity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='fundmovement',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='fundmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Recorded by hand'), ('detected', 'Accepted from a detection')], default='manual', help_text='Typed in by an operator, or accepted from a detection.', max_length=8),
        ),
        migrations.AddField(
            model_name='fundmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fundmovement',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='DetectedMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_equity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('current_equity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('delta', models.DecimalField(decimal_places=8, max_digits=24)),
                ('trade_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('manual_net', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('unexplained', models.DecimalField(decimal_places=8, max_digits=24)),
                ('suggested_kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=12)),
                ('asset', models.CharField(default='USDT', max_length=12)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='accounts.connectedaccount')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='accounts.fundmovement')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['status', 'observed_at'], name='accounts_de_status_a8eea5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, help_text='Username. Blank means the platform itself, not an operator.', max_length=150)),
                ('action', models.CharField(choices=[('detected', 'Detected by the platform'), ('created', 'Recorded by hand'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('accepted', 'Detection accepted'), ('dismissed', 'Detection dismissed'), ('split', 'Profit split changed')], max_length=12)),
                ('account_label', models.CharField(blank=True, max_length=80)),
                ('movement_id', models.IntegerField(blank=True, null=True)),
                ('detection_id', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to='accounts.connectedaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='accounts_le_account_390302_idx')],
            },
        ),
    ]
