# Generated by Django 5.1.5 on 2026-08-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_connectedaccount_last_equity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedmovement',
            name='auto_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='classification_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='confident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='peers_moved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='peers_observed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='suggested_class',
            field=models.CharField(choices=[('trade', 'Trade result'), ('investor', 'Investor cash flow')], default='trade', max_length=10),
        ),
        migrations.AddField(
            model_name='detectedmovement',
            name='traded_in_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detectedmovement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Booked as a cash flow'), ('trade', 'Attributed to the trade'), ('dismissed', 'Dismissed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ledgerevent',
            name='action',
            field=models.CharField(choices=[('detected', 'Detected by the platform'), ('created', 'Recorded by hand'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('accepted', 'Detection accepted'), ('dismissed', 'Detection dismissed'), ('attributed', 'Attributed to trading'), ('reopened', 'Decision reopened'), ('split', 'Profit split changed')], max_length=12),
        ),
    ]
