# Generated by Django 5.1.15 on 2026-08-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_detectedmovement_auto_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='bot_trading_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='manual_trading_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
