# Generated by Django 5.1.4 on 2026-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchdogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.PositiveIntegerField(db_index=True)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — SL attach'), (2, 'Tier 2 — Position protection'), (3, 'Tier 3 — Kill switch')])),
                ('action_type', models.CharField(choices=[('sl_attached', 'SL Attached'), ('position_flat', 'Position Flattened'), ('kill_switch', 'Kill Switch Activated'), ('heartbeat_miss', 'Heartbeat Miss'), ('heartbeat_recover', 'Heartbeat Recovered'), ('position_guardian', 'Position Guardian Check')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchdogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('t_self_ms', models.PositiveIntegerField(default=5000, help_text='Tier 1 threshold (ms)')),
                ('t_dead_ms', models.PositiveIntegerField(default=15000, help_text='Tier 2 threshold (ms)')),
                ('max_blind_hold', models.PositiveIntegerField(default=3, help_text='Max bars to hold blind')),
                ('poll_interval_s', models.PositiveIntegerField(default=5, help_text='Position poll interval (s)')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
