# Generated by Django 5.1.15 on 2026-09-12 21:53

import apps.telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('token_encrypted', models.TextField(blank=True)),
                ('token_fingerprint', models.CharField(blank=True, max_length=16)),
                ('bot_username', models.CharField(blank=True, max_length=64)),
                ('recipient_username', models.CharField(blank=True, max_length=64)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('link_code_hash', models.CharField(blank=True, max_length=64)),
                ('link_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=2)),
                ('groups', models.JSONField(default=apps.telegram.models._all_groups)),
                ('log_cursor', models.BigIntegerField(blank=True, null=True)),
                ('update_offset', models.BigIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'telegram bot',
            },
        ),
    ]
