# Generated by Django 5.1.4 on 2026-07-06 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0004_exchangecredential_api_key_enc_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CopySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "secret_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "default_position_size_pct",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "platform_share_pct",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_size_pct_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "risk_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_subscriptions",
                        to="credentials.exchangecredential",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="copytrading.copysignal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_order_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "client_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("pair", models.CharField(max_length=32)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=8
                    ),
                ),
                ("order_type", models.CharField(default="market", max_length=16)),
                ("size", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=24)),
                (
                    "filled_size",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "avg_fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="copytrading.copysubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopyTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "gross_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "platform_share_amount",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="copytrading.copyorder",
                    ),
                ),
                (
                    "exit_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="copytrading.copyorder",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="copytrading.copysubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=8, max_digits=24)),
                ("equity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_snapshots",
                        to="copytrading.copysubscription",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="copysubscription",
            index=models.Index(
                fields=["signal", "is_active"], name="copytrading_signal__7d0c93_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="copysubscription",
            constraint=models.UniqueConstraint(
                fields=("signal", "credential"), name="uniq_signal_credential"
            ),
        ),
        migrations.AddIndex(
            model_name="copyorder",
            index=models.Index(
                fields=["subscription", "created_at"],
                name="copytrading_subscri_2ecb56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="copytrade",
            index=models.Index(
                fields=["subscription", "status"], name="copytrading_subscri_0d289f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equitysnapshot",
            index=models.Index(
                fields=["subscription", "captured_at"],
                name="copytrading_subscri_a284c4_idx",
            ),
        ),
    ]
