# Generated by Django 5.1.4 on 2026-07-17 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0004_exchangecredential_api_key_and_more"),
        ("strategies", "0007_strategy_is_master_strategy_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fee_rate", models.DecimalField(decimal_places=4, default=Decimal("0.20"), help_text="Fraction of new profit taken as platform fee (0.20 = 20%).", max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CopySignal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("entry", "Entry"), ("close", "Close")], max_length=8)),
                ("direction", models.CharField(blank=True, choices=[("long", "Long"), ("short", "Short"), ("", "None")], default="", max_length=8)),
                ("coin", models.CharField(max_length=32)),
                ("price", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("ts", models.BigIntegerField(help_text="Bar timestamp (ms).")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=64)),
                ("secret_token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("default_position_size_pct", models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ("platform_share_pct", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("master_strategy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="copy_signals", to="strategies.strategy")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_signals", to=settings.AUTH_USER_MODEL)),
                ("strategy", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="copy_signal", to="strategies.strategy")),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sizing_mode", models.CharField(choices=[("risk_pct", "Percent of balance"), ("fixed_notional", "Fixed notional")], default="risk_pct", max_length=16)),
                ("risk_pct", models.DecimalField(decimal_places=3, default=Decimal("1.0"), help_text="Percent of account balance per trade (risk_pct mode).", max_digits=6)),
                ("fixed_notional", models.DecimalField(decimal_places=8, default=Decimal("0"), help_text="Quote-currency notional per trade (fixed_notional mode).", max_digits=20)),
                ("leverage", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credential", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="credentials.exchangecredential")),
                ("investor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to=settings.AUTH_USER_MODEL)),
                ("master_strategy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="strategies.strategy")),
            ],
        ),
        migrations.CreateModel(
            name="CopySubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_size_pct_override", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("risk_factor", models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ("high_water_mark", models.DecimalField(decimal_places=8, default=0, help_text="Cumulative realized profit peak; performance fee is charged only above this.", max_digits=24)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("credential", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="copy_subscriptions", to="credentials.exchangecredential")),
                ("signal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="copytrading.copysignal")),
            ],
        ),
        migrations.CreateModel(
            name="InvestorPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coin", models.CharField(max_length=32)),
                ("size", models.DecimalField(decimal_places=8, help_text="Signed: + long, - short.", max_digits=24)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="positions", to="copytrading.subscription")),
            ],
        ),
        migrations.CreateModel(
            name="FeeLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("realized_pnl", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("high_water_mark", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("fee_accrued", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("fee_rate", models.DecimalField(decimal_places=4, default=Decimal("0.20"), max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="fee_ledger", to="copytrading.subscription")),
            ],
        ),
        migrations.CreateModel(
            name="CopyOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exchange_order_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("client_order_id", models.CharField(blank=True, default="", max_length=64)),
                ("pair", models.CharField(max_length=32)),
                ("side", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=8)),
                ("order_type", models.CharField(default="market", max_length=16)),
                ("size", models.DecimalField(decimal_places=8, max_digits=24)),
                ("price", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("filled_size", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("avg_fill_price", models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="copytrading.copysubscription")),
            ],
        ),
        migrations.CreateModel(
            name="CopyTrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=8)),
                ("gross_pnl", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("platform_share_amount", models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("entry_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="copytrading.copyorder")),
                ("exit_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="copytrading.copyorder")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trades", to="copytrading.copysubscription")),
            ],
        ),
        migrations.CreateModel(
            name="EquitySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=8, max_digits=24)),
                ("equity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equity_snapshots", to="copytrading.copysubscription")),
            ],
        ),
        migrations.CreateModel(
            name="PlatformFeeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("share_pct", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("destination_exchange", models.CharField(default="tabdeal", max_length=16)),
                ("destination_account", models.CharField(blank=True, default="", help_text="Wallet/account the platform's share is owed to.", max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="fee_config", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="FeeLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=8, max_digits=24)),
                ("share_pct", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("status", models.CharField(choices=[("accrued", "Accrued"), ("settled", "Settled")], default="accrued", max_length=8)),
                ("accrued_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fee_entries", to="copytrading.copysubscription")),
                ("trade", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fee_entries", to="copytrading.copytrade")),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(fields=("investor", "master_strategy"), name="uniq_investor_master"),
        ),
        migrations.AddConstraint(
            model_name="investorposition",
            constraint=models.UniqueConstraint(fields=("subscription", "coin"), name="uniq_subscription_coin"),
        ),
        migrations.AddIndex(
            model_name="copysubscription",
            index=models.Index(fields=["signal", "is_active"], name="copytrading_signal__7d0c93_idx"),
        ),
        migrations.AddConstraint(
            model_name="copysubscription",
            constraint=models.UniqueConstraint(fields=("signal", "credential"), name="uniq_signal_credential"),
        ),
        migrations.AddIndex(
            model_name="copyorder",
            index=models.Index(fields=["subscription", "created_at"], name="copytrading_subscri_2ecb56_idx"),
        ),
        migrations.AddIndex(
            model_name="copytrade",
            index=models.Index(fields=["subscription", "status"], name="copytrading_subscri_0d289f_idx"),
        ),
        migrations.AddIndex(
            model_name="equitysnapshot",
            index=models.Index(fields=["subscription", "captured_at"], name="copytrading_subscri_a284c4_idx"),
        ),
        migrations.AddIndex(
            model_name="feeledgerentry",
            index=models.Index(fields=["subscription", "status"], name="copytrading_subscri_b1c2d3_idx"),
        ),
    ]
