# Generated by Django 5.1.4 on 2026-07-17 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0004_exchangecredential_api_key_and_more'),
        ('strategies', '0007_strategy_is_master_strategy_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Fraction of new profit taken as platform fee (0.20 = 20%).', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('close', 'Close')], max_length=8)),
                ('direction', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short'), ('', 'None')], default='', max_length=8)),
                ('coin', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('ts', models.BigIntegerField(help_text='Bar timestamp (ms).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_signals', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizing_mode', models.CharField(choices=[('risk_pct', 'Percent of balance'), ('fixed_notional', 'Fixed notional')], default='risk_pct', max_length=16)),
                ('risk_pct', models.DecimalField(decimal_places=3, default=Decimal('1.0'), help_text='Percent of account balance per trade (risk_pct mode).', max_digits=6)),
                ('fixed_notional', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Quote-currency notional per trade (fixed_notional mode).', max_digits=20)),
                ('leverage', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='credentials.exchangecredential')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('master_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=32)),
                ('size', models.DecimalField(decimal_places=8, help_text='Signed: + long, - short.', max_digits=24)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='copytrading.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('high_water_mark', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('fee_accrued', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledger', to='copytrading.subscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('investor', 'master_strategy'), name='uniq_investor_master'),
        ),
        migrations.AddConstraint(
            model_name='investorposition',
            constraint=models.UniqueConstraint(fields=('subscription', 'coin'), name='uniq_subscription_coin'),
        ),
    ]
