# Generated by Django 5.1.4 on 2026-07-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0001_initial'),
        ('strategies', '0007_strategy_is_master_strategy_published'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feeledgerentry',
            new_name='copytrading_subscri_7acb12_idx',
            old_name='copytrading_subscri_b1c2d3_idx',
        ),
        migrations.AlterField(
            model_name='copysignal',
            name='action',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('close', 'Close')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='copysignal',
            name='coin',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='copysignal',
            name='master_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_signals', to='strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='copysignal',
            name='ts',
            field=models.BigIntegerField(blank=True, help_text='Bar timestamp (ms).', null=True),
        ),
    ]
