# Generated by Django 5.1.4 on 2026-07-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copytrading", "0001_initial"),
        ("strategies", "0006_strategy_credential_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="copysignal",
            name="strategy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_signal",
                to="strategies.strategy",
            ),
        ),
        migrations.AddField(
            model_name="copysubscription",
            name="high_water_mark",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Cumulative realized profit peak; performance fee is charged only above this.",
                max_digits=24,
            ),
        ),
        migrations.CreateModel(
            name="PlatformFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_pct",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "destination_exchange",
                    models.CharField(default="tabdeal", max_length=16),
                ),
                (
                    "destination_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wallet/account the platform's share is owed to.",
                        max_length=128,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "share_pct",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accrued", "Accrued"), ("settled", "Settled")],
                        default="accrued",
                        max_length=8,
                    ),
                ),
                ("accrued_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_entries",
                        to="copytrading.copysubscription",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_entries",
                        to="copytrading.copytrade",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscription", "status"],
                        name="copytrading_subscri_7acb12_idx",
                    )
                ],
            },
        ),
    ]
