# Generated by Django 5.1.4 on 2026-06-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_market_data_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="candle",
            new_name="exchange_ca_network_b4888a_idx",
            old_name="exchange_ca_network_0a8f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="fundingrate",
            new_name="exchange_fu_network_e122d2_idx",
            old_name="exchange_fu_network_6e3b1a_idx",
        ),
        migrations.RenameIndex(
            model_name="openinterest",
            new_name="exchange_op_network_b274b1_idx",
            old_name="exchange_op_network_9d4c7e_idx",
        ),
    ]
