# Generated by Django 5.1.4 on 2026-07-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_rename_exchange_ca_network_0a8f2d_idx_exchange_ca_network_b4888a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='quality',
            field=models.CharField(default='CLEAN', help_text='CLEAN | FLAT | SUSPECT | MISSING — see apps.exchange.data_quality.', max_length=8),
        ),
        migrations.AddField(
            model_name='candle',
            name='trade_count',
            field=models.PositiveIntegerField(default=0, help_text='Raw trades folded into this bar (0 == FLAT).'),
        ),
    ]
