# Generated by Django 5.1.4 on 2026-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_candle_quality_candle_trade_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ledger symbol, e.g. BTC_USDT.', max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether ingest should currently record this market.')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
