//@version=5
strategy("wrapped calls",
         overlay = true,
         precision = 2)
len = input.int(20,
                title = "Length",
                minval = 2,
                maxval = 200)
basis = ta.sma(close,
               len)
if ta.crossover(close,
                basis)
    strategy.entry("L",
                   strategy.long)
plot(basis,
     color = color.blue,
     linewidth = 2)
